version: "3.9"
services:
  web:
    build: server/.
    ports:
      - "5000:5000"
    volumes:
      - ./server/.:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
